### ISSUE TITLE
👾 Farhan and the git-sicles 

### ISSUE THREAD

**Issue by kohasummons** [Farhan001/learnig_git#2]
## A  Trilogy of the Octocat.

And Sodiq 🦸🏽  mastered git, winning the war for the last humans. 🌿 

The end. 📽️

**Comment by Farhan001** [comment]
This guy! :D

**Comment by kohasummons** [comment]
hahaha...
How's it going, bruv

**Comment by kohasummons** [comment]
# 🔥 Git
Yo! checkout [Githubs' lab](https://lab.github.com)
Have yourself some really cool interactive tutorials.

**Comment by Farhan001** [comment]
Going smooth fam.

Thanks for the link big man.

**Comment by kohasummons** [comment]
🔥 🔥
